### ISSUE TITLE
Cave Noire bugs/corrupted save

### ISSUE THREAD

**Issue by codecrundle** [orangeglo/gbnp#25]
Hi there,

I'm not sure if this is actually an issue with GBNP or my GB Memory Cartridge itself (or simply user error) but I'm not sure who else to reach out to regarding this. I've successfully used this tool to create a GBNP file which I've written to my GB Memory Cartridge with GBxCart 1.4a. I did three games, all of which were originally in Japanese that I patched to English. One of them is Cave Noire. IIRC, when I first booted Cave Noire, it assumed it was a brand new game and had me input my character name, I think I went with like "qqqqqqq" at the time. (This is what loads every time I start the game now.) However, there are numerous bugs in-game, such as a Quest 0 Level 0 that shouldn't exist and locks the game up, all 10 levels for each Quest are somehow already unlocked, if I try to wipe the save change my characters name in-game it doesn't actually take. I've tried recompiling the GBNP file, I've tired re-writing the cart, I've tried repatching the ROM itself, I've tried wiping the save from the GBxCart GUI. It always loads up the same corrupted game file and doesn't actually save. I loaded the English patched ROM stand-alone in an emulator and don't have the same issue. I tried loading the GBNP file in an emulator to test it out but unfortunately it doesn't load Cave Noire after I select it in the GB Memory Cartridge's menu. Oh yeah, I'm doing this in Windows 10.

Settings for GBxCart are as follows: (I just left them as default)
-ROM Checksum: 0x19E8
-ROM Size: 1 MiB
-Save Type: 1M SRAM (128kb)
-Mapper Type: G-MMC1
-Cart: NP GB-Memory Cartridge (DMG-MMSA-JPN)

Any tips or help would be greatly appreciated, thanks so much for creating this tool and supporting the community!

**Comment by epbarger** [comment]
Hmm I actually have the english patched Cave Noire on my GB Memory, great game! It sounds to me like your cart _could_ be faulty (likely the SRAM). Here's a list of some things to try...

- Try flashing the patched Cave Noire rom directly to the cart (no menu) and see if you have the same issue. Be sure to wipe the save RAM as well.
- I believe FlashGBX can run a basic SRAM stress test under the "Write Save Data" menu, that would be worth a try to see if you have any issue there.
- What slot in the menu rom is Cave Noire in? If Cave Noire worked when flashed directly (no menu), then try making a new menu rom with Cave Noire in the first slot. If this works, then it's possible your SRAM is having issues in higher address spaces only

Oh and FYI it's normal that the GBNP menu roms don't launch games in the emulator - that's expected since the carts have special hardware on them that the emulators don't fake.

I hope you can figure it out! Let me know what happens and if it seems like an issue with GBNP I'm happy to take a look.

**Comment by codecrundle** [comment]
@epbarger Thanks for the detailed write up! Here are the results:

- Erased save data and wrote ROM directly to cart, same issue.
- Great idea on the stress test, mine failed Test 2 (writing random values)

I just opened up the cart, I had no idea there was a battery in this sucker. I assumed SRAM = no battery? Looks to be a CR2025 and I think it's original. Luckily, I have some tabbed CR2025's on hand and will soldering it in shortly. Not entirely sure if this is the root of my problem but I could use the soldering practice and enjoy it anyways, haha. Will report back with results!

**Comment by codecrundle** [comment]
Woops, didn't mean to close out my ticket. But in any case, this clearly isn't a problem with GBNP lol.

Edit: Replaced the battery, it no longer fails the save stress test but the problem persists. I gotta do more research on how gb game cartridges function and how SRAM memory is stored...but it sounds like mine may be faulty?

**Comment by epbarger** [comment]
Do you use Discord? There is a game boy discord that has a troubleshooting channel where some folk may help you investigate the issue. https://discord.gg/72TsN9Km

It does sound like it's probably an issue with your SRAM. The battery only matters for retention of the SRAM data, it shouldn't affect the GBxCart test. But obviously you want your save data to be retained :)

I'd check the circuit board for any obvious signs of corrosion or damaged traces leading to the SRAM chip. You could also _carefully_ reflow the solder connections on the chip if you're confident

**Comment by codecrundle** [comment]
I do, I'll come join! I examined the board closely, nothing I can tell is amiss. I'm gonna grab my magnifying glass and check the traces more closely though. I have a multimeter too, I should probably check for continuity and whatnot. Reflowing the chip(s) is actually something I've been meaning to do on another cart I'm having issues with, I think I'll practice on another board first though.
