### ISSUE TITLE
Japanese Characters do not display correctly

### ISSUE THREAD

**Issue by alan-morford** [orangeglo/gbnp#5]
I've attached some pics. The one with 3 titles was written using your awesome web tool. The one with the single file is stock. Both top titles are the same game super mario land 3. Notice how the fonts do no display the same. Changing the fonts available on your tool does not make it show up correctly. I can't read the japanese characters. How can this be fixed? 

![1](https://user-images.githubusercontent.com/8835583/108595503-890bc900-73c3-11eb-93f9-668d3276a0d9.jpg)
![2](https://user-images.githubusercontent.com/8835583/108595507-8c06b980-73c3-11eb-8aa8-90fda3078c6d.jpg)

**Comment by epbarger** [comment]
Hey @alan-morford !

None of the fonts on the site currently support Japanese katakana or hiragana characters to my knowledge. I'm actually surprised you're getting what looks like valid characters, just not rendered correctly because the font size is too small? What font did you have selected in that photo?

I need to do more research to figure out the best way to add support. I'm thinking of adding support for the Pokemon KT and Pokemon HR fonts from https://www.fontspace.com/pokemon-gb-font-f9621, since that seems the most likely to fit. Unfortunately the current font system needs fonts that fit entirely within 8px height -  and I've never found a Japanese pixel font that seems to fit this restriction. However, I think I can do some reworking of the font system to allow for overhang into the next row, which I think would solve the problem for some fonts. IIRC I think this is what the original kiosk font does on occasion.

Would you be willing to help me test JP font support in the future?

**Comment by epbarger** [comment]
Ah I see, if you type Japanese characters in, you'll just get the default system font rendering them, which since it's not a pixel font, doesn't map nicely onto the gameboy. I tried adding this [7px katakana font](https://www.fontspace.com/7pxkbus-font-f3831) as an experiment, and here are the results. It seems like a lot of JP pixel fonts that I can find are mapped to a-z on an english keyboard? Is that correct? I don't know much about the Japanese language.

How does this look?
<img width="1365" alt="Screen Shot 2021-02-20 at 2 45 07 PM" src="https://user-images.githubusercontent.com/2780987/108606902-09fa9e80-738b-11eb-94cf-9cd40a34f782.png">

**Comment by alan-morford** [comment]
Sorry it took me so long to respond. Thank you for jumping on this quickly. That font does look better but is still pretty hard to read. Perhaps there's another font that will work better. I wonder how the font was added on an original kiosk. Is it possible to tell from the files from an NPC or backup? 

I am happy to help you test anything with NPC.

**Comment by alan-morford** [comment]
Here's a font that may work better. https://www.fontspace.com/enikusu-hg-font-f2402

**Comment by alan-morford** [comment]
As far as the keyboard is concerned, here's how they appear on a keyboard https://en.wikipedia.org/wiki/Language_input_keys#/media/File:KB_Japanese.svg

**Comment by epbarger** [comment]
Awesome, thanks for the follow up. I'll try integrating that font and get back to you. I'm concerned that font might use too much vertical space though, looks like it can use up to 10px vertically, when really we have 8px to work with

**Comment by epbarger** [comment]
Hey @alan-morford I just merged in a 7px font "NP GBメモリ" which should be quite close to the original font used on the cart. Give it a shot! "Lesserkuma" on the insideGadgets discord has been working to make a replica font that's as close to the original GBNP font as possible, and this is the first version based on a game he found that is 90% the same

**Comment by alan-morford** [comment]
Yes! I discussed this with them via PM on Discord. I have a few GBC files
to send to be reviewed for missing characters. They use pictures instead of
fonts! So odd. I'll give your site a check in a bit. Thanks.

**Comment by epbarger** [comment]
Closed since we've added the GB Memory recreation font :)
